name: 'Generate PHP docs with clean/phpdoc-md'
description: 'GitHub action to generate PHP project documentation in MarkDown format. Based on clean/phpdoc-md library.'

branding:
  icon: book
  color: blue

inputs:
  output_path:
    description: "Path where to write generated documentation"
    required: true
  class_root_namespace:
    description: "Root class namespace"
    required: true
  included_classes:
    description: "Included classes list (supports glob style wildcards syntax; each line means one rule)"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setting env variables...
      env:
        GENERATOR_TMP_SUFIX: ${{ github.sha }}-${{ github.run_id }}-${{ github.github.run_attempt }}
        GENERATOR_TMP_PATH: ${{ runner.temp }}
        ACTION_BIN_PATH: ${{ github.action_path }}/bin
      run: $ACTION_BIN_PATH/generate-env.sh "$GENERATOR_TMP_SUFIX" "$GENERATOR_TMP_PATH" "$ACTION_BIN_PATH" >> $GITHUB_ENV
      shell: bash
  
    - name: Creating tmp folders
      run: $ACTION_BIN_PATH/create-temp-folders.sh
      shell: bash

    - name: Copying current project to tmp folder...
      run: $ACTION_BIN_PATH/copy-current-project-to-tmp-folder.sh
      shell: bash

    - name: Getting PHP class list...
      uses: impresscms-dev/generate-php-project-classes-list-file-action@v1.0.1
      with:
        output_file: ${{ env.PHP_CLASSES_ORIG_FILE }}

    - name: Generating temp filtering rules file...
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: ${{ env.RULES_FILE }}
        contents: "${{ inputs.included_classes }}"
        write-mode: overwrite

    - name: Filtering PHP classes list...
      uses: impresscms-dev/filter-php-class-list-with-glob-like-rules-action@v1.0.0
      with:
        rules_file: ${{ env.RULES_FILE }}
        input_file: ${{ env.PHP_CLASSES_ORIG_FILE }}
        output_file: ${{ env.PHP_CLASSES_FILTERED_FILE }}

    - name: Generating generator config...
      env:
        PHPDOCMD_FILE: ${{ env.COPY_DATA_PATH }}/.phpdoc-md
        CLASS_ROOT_NAMESPACE: ${{ inputs.class_root_namespace }}
        DOCS_PATH: ${{ inputs.output_path }}
      run: $ACTION_BIN_PATH/generate-config.php "$PHPDOCMD_FILE" "$PHP_CLASSES_FILTERED_FILE" "$CLASS_ROOT_NAMESPACE" "$DOCS_PATH"
      shell: bash

    - name: Including documentation generator...
      run: $ACTION_BIN_PATH/add-composer-packages.sh
      shell: bash

    - name: Generating documentation...
      run: $ACTION_BIN_PATH/generate-docs.sh
      shell: bash

    - name: Deleting tmp data...
      run: $ACTION_BIN_PATH/delete-temp-folders.sh
      shell: bash
